from .register_kb import register_menu
from .main_menu_kb import main_menu
from .settings_menu_kb import settings_menu
from .account_settings_menu_kb import account_settings_menu
from .delete_account_answers_kb import delete_account_answers_menu
from .sendall_settings_menu_kb import sendall_settings_menu
from .sendall_switch_menu_kb import sendall_switch_menu
from .help_menu_kb import help_menu
from .help_admin_menu_kb import help_admin_menu